In [2]:
import pandas as pd
import openpyxl
import numpy as np

In [2]:
# access data from repo
repo = "https://raw.githubusercontent.com/walde363/covid-housing-forecast/main/"
folder = "data/raw/"

urls = {
    "hurricanes": f"{repo}{folder}Huricanes.csv",
    "unemployment": f"{repo}{folder}Unemployment%20rate%20-%20FL.csv",
    "building_permits": f"{repo}{folder}New%20housing%20building%20permits%20-%20FL.csv",
    "mortgage_rates": f"{repo}{folder}historicalweeklydata_morgage_rates.xlsx",
    "hpi": f"{repo}{folder}hpi_po_monthly_hist.xlsx",
    "investor": f"{repo}{folder}dowload_investor_purchases_by_metro.csv",

    "metro_inventory_week": f"{repo}{folder}Metro_invt_fs_uc_sfr_week.csv",
    "metro_days_to_close_sm_week": f"{repo}{folder}Metro_mean_days_to_close_uc_sfrcondo_sm_week.csv",
    "metro_days_to_close_week": f"{repo}{folder}Metro_mean_days_to_close_uc_sfrcondo_week.csv",

    "metro_market_temp_month": f"{repo}{folder}Metro_market_temp_index_uc_sfrcondo_month.csv",
    "metro_new_con_sales_month": f"{repo}{folder}Metro_new_con_sales_count_raw_uc_sfrcondo_month.csv",
    "metro_zhvi_tier_month": f"{repo}{folder}Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_month.csv",
    "metro_zordi_condo_month": f"{repo}{folder}Metro_zordi_uc_condo_month.csv",
    "metro_zordi_mfr_month": f"{repo}{folder}Metro_zordi_uc_mfr_month.csv",
    "metro_zordi_sfr_month": f"{repo}{folder}Metro_zordi_uc_sfr_month.csv",
    "metro_zordi_all_month": f"{repo}{folder}Metro_zordi_uc_sfrcondomfr_month.csv",
    
    "merged_bls_long": f"{repo}{folder}merged_bls_long.csv",
    "merged_bls_wide": f"{repo}{folder}merged_bls_wide.csv",
    "BLS_unemployment_data": f"{repo}{folder}BLS_unemployment_data.csv",
    "BLS_weekly_earnings": f"{repo}{folder}BLS_weekly_earnings.csv",
    
    "RDC_FL_Metrics_County": f"{repo}{folder}RDC_FL_Metrics_County.csv",
    "RDC_FL_Metrics_Metro": f"{repo}{folder}RDC_FL_Metrics_Metro.csv",
    "RDC_Inventory_Core_Metrics_Country_History": f"{repo}{folder}RDC_Inventory_Core_Metrics_Country_History.csv",
    "RDC_Inventory_Core_Metrics_State_History": f"{repo}{folder}RDC_Inventory_Core_Metrics_State_History.csv",
    "Supporting_Underlying_Metrics_and_Disclaimer_for_Analyses_of_US_Homeowners_Insurance_Markets_2018-2022": f"{repo}{folder}Supporting_Underlying_Metrics_and_Disclaimer_for_Analyses_of_US_Homeowners_Insurance_Markets_2018-2022.xlsx",
}

def load_csv_with_fallback(url):
    # Handle mixed file exports: encoding issues and malformed rows.
    for encoding in ["utf-8", "utf-8-sig", "utf-16", "latin1"]:
        try:
            return pd.read_csv(url, encoding=encoding)
        except UnicodeDecodeError:
            continue
        except pd.errors.ParserError:
            try:
                return pd.read_csv(
                    url,
                    encoding=encoding,
                    sep=None,
                    engine="python",
                    on_bad_lines="skip"
                )
            except (UnicodeDecodeError, pd.errors.ParserError):
                continue

    raise ValueError(f"Could not parse CSV with supported settings: {url}")

def load_data(url):
    if url.endswith(".csv"):
        return load_csv_with_fallback(url)
    elif url.endswith(".xlsx"):
        return pd.read_excel(url)
    else:
        raise ValueError(f"Unsupported file format: {url}")

data = {name: load_data(url) for name, url in urls.items()}

In [3]:
## Open https://www.aoml.noaa.gov/hrd/hurdat/All_U.S._Hurricanes.html 
## Copy and paste table to a google sheet
## Download sheet as a csv
hurricanes_df = data["hurricanes"]

## Open https://fred.stlouisfed.org/series/FLUR
## Press 10Y to limit to 10 years
## Press download
## Press csv
unemployment_df = data["unemployment"]

## Go to  https://fred.stlouisfed.org/series/FLBP1FH 
## Press 10Y to limit to 10 years
## Press download
## Press csv
fl_building_permits_df = data["building_permits"]

## Go to https://www.freddiemac.com/pmms?utm_source
## Press Download Rates Since 1971 XLSX
mortgage_rates_df = data["mortgage_rates"]

## Go to https://www.fhfa.gov/data/hpi/datasets
## Select U.S. and Census Division (Seasonally Adjusted and Not Adjusted) January 1991 - Latest Month    
hpi_df = data["hpi"]

## Go to https://www.redfin.com/news/data-center/investor-data/
## Directly under the words "Investor Purchases" click on Download Data
## Underneath the table click the box with an arrow pointing down
## Click cross tab
## Select CSV
## Press download
investor_df = data["investor"]

## Go to https://www.zillow.com/research/data/
## Navigate to dataset section on the page
## Select the data type and given geography
## Press download
metro_inventory_week_df        = data["metro_inventory_week"]
metro_days_to_close_sm_week_df = data["metro_days_to_close_sm_week"]
metro_market_temp_month_df     = data["metro_market_temp_month"]
metro_new_con_sales_month_df   = data["metro_new_con_sales_month"]
metro_zhvi_tier_month_df       = data["metro_zhvi_tier_month"]
metro_zordi_condo_month_df     = data["metro_zordi_condo_month"]
metro_zordi_mfr_month_df       = data["metro_zordi_mfr_month"]
metro_zordi_sfr_month_df       = data["metro_zordi_sfr_month"]
metro_zordi_all_month_df       = data["metro_zordi_all_month"]

merged_bls_long_df = data["merged_bls_long"]
merged_bls_wide_df = data["merged_bls_wide"]
BLS_unemployment_data_df = data["BLS_unemployment_data"]
BLS_weekly_earnings_df = data["BLS_weekly_earnings"]

RDC_FL_Metrics_County_df = data["RDC_FL_Metrics_County"]
RDC_FL_Metrics_Metro_df = data["RDC_FL_Metrics_Metro"]
RDC_Inventory_Core_Metrics_Country_History_df = data["RDC_Inventory_Core_Metrics_Country_History"]
RDC_Inventory_Core_Metrics_State_History_df = data["RDC_Inventory_Core_Metrics_State_History"]

Supporting_Underlying_Metrics_and_Disclaimer_for_Analyses_of_US_Homeowners_Insurance_Markets_2018_2022_df = data["Supporting_Underlying_Metrics_and_Disclaimer_for_Analyses_of_US_Homeowners_Insurance_Markets_2018-2022"]

In [4]:
def review_datasets(data_dict):
    for name, df in data_dict.items():
        print("="*60)
        print(f"Dataset: {name}")
        print("="*60)

        # Shape
        print(f"Shape: {df.shape[0]} rows × {df.shape[1]} columns\n")

        # Data types
        print("Data Types:")
        print(df.dtypes)
        print()

        # Missing values
        missing = df.isnull().sum()
        missing_percent = (missing / len(df)) * 100

        missing_df = pd.DataFrame({
            "Missing Values": missing,
            "Percent (%)": missing_percent
        })

        print("Missing Values:")
        print(missing_df[missing_df["Missing Values"] > 0])
        print()

        # Duplicate rows
        duplicates = df.duplicated().sum()
        print(f"Duplicate Rows: {duplicates}\n")

        # Summary statistics (numeric columns only)
        print("Summary Statistics:")
        print(df.describe())
        print("\n\n")

## Data processing

In [5]:
# remove rows that contain s. This is a row to separate years
hurricanes_df_clean = hurricanes_df.copy(deep=True)
hurricanes_df_clean = hurricanes_df_clean[~hurricanes_df_clean["ar"].str.contains(r"[A-Za-z]", na=False)]

# flag rows with FL
hurricanes_df_clean["fl_flag"] = hurricanes_df_clean["States Affected and Category by States"].str.contains("FL", na=False)

hurricanes_df_clean = hurricanes_df_clean.rename(columns={
    'ar': 'year',
    'Highest\nSaffir-\nSimpson\nU.S. Category': 'highest_category'
})

#filter to FL
hurricanes_df_clean = hurricanes_df_clean[hurricanes_df_clean['fl_flag'] == True]

In [6]:
month_map = {
    "Jan": 1, "Feb": 2, "Mar": 3,
    "Apr": 4, "May": 5, "Jun": 6,
    "Jul": 7, "Aug": 8, "Sep": 9,
    "Oct": 10, "Nov": 11, "Dec": 12
}

# Make this cell safe to re-run: only expand when the raw Month column exists.
if "Month" in hurricanes_df_clean.columns:
    def expand_month(row):
        month_value = row["Month"]

        if month_value == "Sp-Oc":
            months = [9, 10]
        elif month_value == "Jl-Au":
            months = [7, 8]
        else:
            months = [month_map[month_value]]

        return pd.DataFrame({
            "year": row["year"],
            "month": months,
            "highest_category": pd.to_numeric(row["highest_category"], errors="coerce")
        })

    hurricanes_df_clean = pd.concat(
        hurricanes_df_clean.apply(expand_month, axis=1).tolist(),
        ignore_index=True
    )
elif {"year", "month", "highest_category"}.issubset(hurricanes_df_clean.columns):
    hurricanes_df_clean = hurricanes_df_clean.copy()
else:
    raise KeyError(
        "Expected either raw hurricane columns including 'Month' or transformed columns: "
        "'year', 'month', 'highest_category'."
    )

In [7]:
unemployment_df_clean = unemployment_df.copy(deep=True)
unemployment_df_clean = unemployment_df_clean[unemployment_df_clean['FLUR'].notnull()]

In [8]:
fl_building_permits_df_clean = fl_building_permits_df.copy(deep=True)
fl_building_permits_df_clean["observation_date"] = pd.to_datetime(fl_building_permits_df_clean["observation_date"])
fl_building_permits_df_clean["year"] = fl_building_permits_df_clean["observation_date"].dt.year
fl_building_permits_df_clean["month"] = fl_building_permits_df_clean["observation_date"].dt.month

In [9]:
mortgage_rates_df_clean = mortgage_rates_df.copy(deep=True)
mortgage_rates_df_clean = mortgage_rates_df_clean[mortgage_rates_df_clean['Unnamed: 0'].notnull()]

# take first row as header
mortgage_rates_df_clean.columns = mortgage_rates_df_clean.iloc[0]
mortgage_rates_df_clean = mortgage_rates_df_clean[1:].reset_index(drop=True)

week_parsed = pd.to_datetime(mortgage_rates_df_clean["Week"], errors="coerce")
mortgage_rates_df_clean = mortgage_rates_df_clean[week_parsed.notna()].copy()
mortgage_rates_df_clean["Week"] = week_parsed[week_parsed.notna()].dt.date

# renaming columns from base spreedsheet
mortgage_rates_df_clean.columns.values[0] = "Week"
mortgage_rates_df_clean.columns.values[1] = "U.S. 30 year FRM"
mortgage_rates_df_clean.columns.values[2] = "30 year fees & points"

mortgage_rates_df_clean.columns.values[3] = "U.S. 15 year FRM"
mortgage_rates_df_clean.columns.values[4] = "15 year fees & points"

mortgage_rates_df_clean.columns.values[5] = "U.S. 5/1 ARM"
mortgage_rates_df_clean.columns.values[6] = "5/1 year fees & points"

mortgage_rates_df_clean.columns.values[7] = "U.S. 5/1 ARM margin"
mortgage_rates_df_clean.columns.values[8] = "30 year FRM / 5/1 ARM spread"

#Truncate
mortgage_rates_df_clean = mortgage_rates_df_clean[mortgage_rates_df_clean['Week']>=pd.to_datetime("2016-01-01").date()]

unemployment_df_clean["observation_date"] = pd.to_datetime(unemployment_df_clean["observation_date"])
unemployment_df_clean["year"] = unemployment_df_clean["observation_date"].dt.year
unemployment_df_clean["month"] = unemployment_df_clean["observation_date"].dt.month

In [10]:
hpi_df_clean = hpi_df.copy(deep=True)

hpi_df_clean.columns = hpi_df_clean.iloc[2]
# Drop the first three rows
hpi_df_clean = hpi_df_clean.iloc[3:].reset_index(drop=True)


week_parsed = pd.to_datetime(hpi_df_clean["Month"], errors="coerce")
hpi_df_clean = hpi_df_clean[week_parsed.notna()].copy()
hpi_df_clean["Month"] = week_parsed[week_parsed.notna()].dt.date
hpi_df_clean.columns = hpi_df_clean.columns.str.replace('\n', ' ')
hpi_df_clean = pd.melt(hpi_df_clean, id_vars="Month", var_name="Location", value_name="HPI")

hpi_df_clean["observation_date"] = pd.to_datetime(hpi_df_clean["Month"])
hpi_df_clean["year"] = hpi_df_clean["observation_date"].dt.year
hpi_df_clean["month"] = hpi_df_clean["observation_date"].dt.month

In [11]:
investor_df_clean = investor_df.copy(deep=True)

# Split year and quarter
investor_df_clean[["year", "q"]] = investor_df_clean["Quarter"].str.split(" ", expand=True)

investor_df_clean["year"] = investor_df_clean["year"].astype(int)
investor_df_clean["quarter"] = investor_df_clean["q"].str.replace("Q", "").astype(int)

# Convert quarter → starting month
investor_df_clean["month"] = (investor_df_clean["quarter"] - 1) * 3 + 1

# Create datetime (quarter start)
investor_df_clean["date"] = pd.to_datetime(
    dict(year=investor_df_clean["year"], month=investor_df_clean["month"], day=1)
)

investor_df_clean["Investor Purchases"] = (
    investor_df_clean["Investor Purchases"]
    .str.replace(",", "", regex=False)
    .astype("Int32")
)

investor_df_clean["Investor Market Share"] = (
    investor_df_clean["Investor Market Share"]
    .str.replace("%", "", regex=False)
    .astype("Int32")
)

investor_df_clean["Investor Purchases YoY"] = (
    investor_df_clean["Investor Purchases YoY"]
    .str.replace("%", "", regex=False)
    .astype("Int32")
)

investor_df_clean = investor_df_clean.groupby(["year", "month", "date", "Redfin Metro"]).agg(
    {"Investor Purchases": "sum"
    ,"Investor Market Share": "mean"
    ,"Investor Purchases YoY": "mean"}).reset_index()

investor_df_clean[['city', 'state']] = investor_df_clean['Redfin Metro'].str.split(',', expand=True)
investor_df_clean = investor_df_clean.groupby(["date","state"]).agg({"Investor Purchases": "sum", "Investor Market Share": "mean", "Investor Purchases YoY": "mean"}).reset_index()

In [12]:
metro_inventory_week_df_clean = metro_inventory_week_df.copy(deep=True)
metro_inventory_week_df_clean = pd.melt(
    metro_inventory_week_df_clean,
    id_vars=["RegionID", "SizeRank", "RegionName", "RegionType","StateName"],
    var_name="Week",
    value_name="Inventory"
)

metro_inventory_week_df_clean = metro_inventory_week_df_clean[metro_inventory_week_df_clean["Inventory"].notnull()]

metro_inventory_week_df_clean["Week"] = pd.to_datetime(metro_inventory_week_df_clean["Week"])
metro_inventory_week_df_clean["year"] = metro_inventory_week_df_clean["Week"].dt.year
metro_inventory_week_df_clean["month"] = metro_inventory_week_df_clean["Week"].dt.month

metro_inventory_week_df_clean = metro_inventory_week_df_clean[metro_inventory_week_df_clean["Inventory"].notnull()]

metro_inventory_week_df_clean = metro_inventory_week_df_clean.groupby(["RegionID", "SizeRank", "RegionName", "RegionType", "StateName", "year", "month"])["Inventory"].mean().reset_index()

In [13]:
metro_days_to_close_sm_week_df_clean = metro_days_to_close_sm_week_df.copy(deep=True)
metro_days_to_close_sm_week_df_clean = pd.melt(
    metro_days_to_close_sm_week_df_clean,
    id_vars=["RegionID", "SizeRank", "RegionName", "RegionType","StateName"],
    var_name="Week",
    value_name="DaysToClose"
)

metro_days_to_close_sm_week_df_clean = metro_days_to_close_sm_week_df_clean[metro_days_to_close_sm_week_df_clean["DaysToClose"].notnull()]
metro_days_to_close_sm_week_df_clean["Week"] = pd.to_datetime(metro_days_to_close_sm_week_df_clean["Week"])
metro_days_to_close_sm_week_df_clean["year"] = metro_days_to_close_sm_week_df_clean["Week"].dt.year
metro_days_to_close_sm_week_df_clean["month"] = metro_days_to_close_sm_week_df_clean["Week"].dt.month
metro_days_to_close_sm_week_df_clean = metro_days_to_close_sm_week_df_clean[metro_days_to_close_sm_week_df_clean["DaysToClose"].notnull()]
metro_days_to_close_sm_week_df_clean = metro_days_to_close_sm_week_df_clean.groupby(["RegionID", "SizeRank", "RegionName", "RegionType", "StateName", "year", "month"])["DaysToClose"].mean().reset_index()

In [14]:
metro_market_temp_month_df_clean = metro_market_temp_month_df.copy(deep=True)
metro_market_temp_month_df_clean = pd.melt(
    metro_market_temp_month_df_clean,
    id_vars=["RegionID", "SizeRank", "RegionName", "RegionType","StateName"],
    var_name="Month",
    value_name="MarketTemp"
)

metro_market_temp_month_df_clean = metro_market_temp_month_df_clean[metro_market_temp_month_df_clean["MarketTemp"].notnull()]

metro_market_temp_month_df_clean["Month"] = pd.to_datetime(metro_market_temp_month_df_clean["Month"])
metro_market_temp_month_df_clean["year"] = metro_market_temp_month_df_clean["Month"].dt.year
metro_market_temp_month_df_clean["month"] = metro_market_temp_month_df_clean["Month"].dt.month

In [15]:
metro_new_con_sales_month_df_clean = metro_new_con_sales_month_df.copy(deep=True)
metro_new_con_sales_month_df_clean = pd.melt(
    metro_new_con_sales_month_df_clean,
    id_vars=["RegionID", "SizeRank", "RegionName", "RegionType","StateName"],
    var_name="Month",
    value_name="NewConSales"
)

metro_new_con_sales_month_df_clean = metro_new_con_sales_month_df_clean[metro_new_con_sales_month_df_clean["NewConSales"].notnull()]

metro_new_con_sales_month_df_clean["Month"] = pd.to_datetime(metro_new_con_sales_month_df_clean["Month"])
metro_new_con_sales_month_df_clean["year"] = metro_new_con_sales_month_df_clean["Month"].dt.year
metro_new_con_sales_month_df_clean["month"] = metro_new_con_sales_month_df_clean["Month"].dt.month

In [16]:
metro_zhvi_tier_month_df_clean = metro_zhvi_tier_month_df.copy(deep=True)
metro_zhvi_tier_month_df_clean = pd.melt(
    metro_zhvi_tier_month_df_clean,
    id_vars=["RegionID", "SizeRank", "RegionName", "RegionType","StateName"],
    var_name="Month",
    value_name="ZHVI_Tier"
)

metro_zhvi_tier_month_df_clean = metro_zhvi_tier_month_df_clean[metro_zhvi_tier_month_df_clean["ZHVI_Tier"].notnull()]

metro_zhvi_tier_month_df_clean["Month"] = pd.to_datetime(metro_zhvi_tier_month_df_clean["Month"])
metro_zhvi_tier_month_df_clean["year"] = metro_zhvi_tier_month_df_clean["Month"].dt.year
metro_zhvi_tier_month_df_clean["month"] = metro_zhvi_tier_month_df_clean["Month"].dt.month

In [17]:
metro_zordi_condo_month_df_clean = metro_zordi_condo_month_df.copy(deep=True)
metro_zordi_condo_month_df_clean = pd.melt(
    metro_zordi_condo_month_df_clean,
    id_vars=["RegionID", "SizeRank", "RegionName", "RegionType","StateName"],
    var_name="Month",
    value_name="ZORDI_Condo"
)

metro_zordi_condo_month_df_clean = metro_zordi_condo_month_df_clean[metro_zordi_condo_month_df_clean["ZORDI_Condo"].notnull()]

metro_zordi_condo_month_df_clean["Month"] = pd.to_datetime(metro_zordi_condo_month_df_clean["Month"])
metro_zordi_condo_month_df_clean["year"] = metro_zordi_condo_month_df_clean["Month"].dt.year
metro_zordi_condo_month_df_clean["month"] = metro_zordi_condo_month_df_clean["Month"].dt.month

In [18]:
metro_zordi_mfr_month_df_clean = metro_zordi_mfr_month_df.copy(deep=True)
metro_zordi_mfr_month_df_clean = pd.melt(
    metro_zordi_mfr_month_df_clean,
    id_vars=["RegionID", "SizeRank", "RegionName", "RegionType","StateName"],
    var_name="Month",
    value_name="ZORDI_MFR"
)

metro_zordi_mfr_month_df_clean = metro_zordi_mfr_month_df_clean[metro_zordi_mfr_month_df_clean["ZORDI_MFR"].notnull()]

metro_zordi_mfr_month_df_clean["Month"] = pd.to_datetime(metro_zordi_mfr_month_df_clean["Month"])
metro_zordi_mfr_month_df_clean["year"] = metro_zordi_mfr_month_df_clean["Month"].dt.year
metro_zordi_mfr_month_df_clean["month"] = metro_zordi_mfr_month_df_clean["Month"].dt.month

In [19]:
metro_zordi_sfr_month_df_clean = metro_zordi_sfr_month_df.copy(deep=True)
metro_zordi_sfr_month_df_clean = pd.melt(
    metro_zordi_sfr_month_df_clean,
    id_vars=["RegionID", "SizeRank", "RegionName", "RegionType","StateName"],
    var_name="Month",
    value_name="ZORDI_SFR"
)

metro_zordi_sfr_month_df_clean = metro_zordi_sfr_month_df_clean[metro_zordi_sfr_month_df_clean["ZORDI_SFR"].notnull()]

metro_zordi_sfr_month_df_clean["Month"] = pd.to_datetime(metro_zordi_sfr_month_df_clean["Month"])
metro_zordi_sfr_month_df_clean["year"] = metro_zordi_sfr_month_df_clean["Month"].dt.year
metro_zordi_sfr_month_df_clean["month"] = metro_zordi_sfr_month_df_clean["Month"].dt.month

In [20]:
metro_zordi_all_month_df_clean = metro_zordi_all_month_df.copy(deep=True)
metro_zordi_all_month_df_clean = pd.melt(
    metro_zordi_all_month_df_clean,
    id_vars=["RegionID", "SizeRank", "RegionName", "RegionType","StateName"],
    var_name="Month",
    value_name="ZORDI_All"
)

metro_zordi_all_month_df_clean = metro_zordi_all_month_df_clean[metro_zordi_all_month_df_clean["ZORDI_All"].notnull()]

metro_zordi_all_month_df_clean["Month"] = pd.to_datetime(metro_zordi_all_month_df_clean["Month"])
metro_zordi_all_month_df_clean["year"] = metro_zordi_all_month_df_clean["Month"].dt.year
metro_zordi_all_month_df_clean["month"] = metro_zordi_all_month_df_clean["Month"].dt.month

In [21]:
print(hurricanes_df_clean.isna().sum(), "\n")
print(unemployment_df_clean.isna().sum(), "\n")
print(fl_building_permits_df_clean.isna().sum(), "\n")
print(mortgage_rates_df_clean.isna().sum(), "\n")
print(hpi_df_clean.isna().sum(), "\n")
print(investor_df_clean.isna().sum(), "\n")
print(metro_inventory_week_df_clean.isna().sum(), "\n")
print(metro_days_to_close_sm_week_df_clean.isna().sum(), "\n")
print(metro_market_temp_month_df_clean.isna().sum(), "\n")
print(metro_new_con_sales_month_df_clean.isna().sum(), "\n")
print(metro_zhvi_tier_month_df_clean.isna().sum(), "\n")
print(metro_zordi_condo_month_df_clean.isna().sum(), "\n")
print(metro_zordi_mfr_month_df_clean.isna().sum(), "\n")
print(metro_zordi_sfr_month_df_clean.isna().sum(), "\n")
print(metro_zordi_all_month_df_clean.isna().sum(), "\n")

year                0
month               0
highest_category    1
dtype: int64

observation_date    0
FLUR                0
year                0
month               0
dtype: int64

observation_date    0
FLBP1FH             0
year                0
month               0
dtype: int64

5
Week                              0
U.S. 30 year FRM                  0
30 year fees & points           173
U.S. 15 year FRM                  0
15 year fees & points           173
U.S. 5/1 ARM                    173
5/1 year fees & points          173
U.S. 5/1 ARM margin             173
30 year FRM / 5/1 ARM spread    173
dtype: int64

Month               0
Location            0
HPI                 0
observation_date    0
year                0
month               0
dtype: int64

date                       0
state                      0
Investor Purchases         0
Investor Market Share      0
Investor Purchases YoY    88
dtype: int64

RegionID      0
SizeRank      0
RegionName    0
RegionType    0
StateName     0
year          0
month         0
Inventory     0
dtype: int64

RegionID       0
SizeRank       0
RegionName     0
RegionType     0
StateName      0
year           0
month          0
DaysToClose    0
dtype: int64

RegionID       0
SizeRank       0
RegionName     0
RegionType     0
StateName     97
Month          0
MarketTemp     0
year           0
month          0
dtype: int64

RegionID        0
SizeRank        0
RegionName      0
RegionType      0
StateName      96
Month           0
NewConSales     0
year            0
month           0
dtype: int64

RegionID        0
SizeRank        0
RegionName      0
RegionType      0
StateName     360
Month           0
ZHVI_Tier       0
year            0
month           0
dtype: int64

RegionID        0
SizeRank        0
RegionName      0
RegionType      0
StateName      68
Month           0
ZORDI_Condo     0
year            0
month           0
dtype: int64

RegionID       0
SizeRank       0
RegionName     0
RegionType     0
StateName     68
Month          0
ZORDI_MFR      0
year           0
month          0
dtype: int64

RegionID       0
SizeRank       0
RegionName     0
RegionType     0
StateName     68
Month          0
ZORDI_SFR      0
year           0
month          0
dtype: int64

RegionID       0
SizeRank       0
RegionName     0
RegionType     0
StateName     68
Month          0
ZORDI_All      0
year           0
month          0
dtype: int64

In [22]:
hurricanes_df_clean["date"] = pd.to_datetime(
    dict(year=hurricanes_df_clean["year"], month=hurricanes_df_clean["month"], day=1)
)

unemployment_df_clean["date"] = pd.to_datetime(
    dict(year=unemployment_df_clean["year"], month=unemployment_df_clean["month"], day=1)
)

fl_building_permits_df_clean["date"] = pd.to_datetime(
    dict(year=fl_building_permits_df_clean["year"], month=fl_building_permits_df_clean["month"], day=1)
)

hpi_df_clean["date"] = pd.to_datetime(
    dict(year=hpi_df_clean["year"], month=hpi_df_clean["month"], day=1)
)

metro_inventory_week_df_clean["date"] = pd.to_datetime(
    dict(year=metro_inventory_week_df_clean["year"], month=metro_inventory_week_df_clean["month"], day=1)
)

metro_days_to_close_sm_week_df_clean["date"] = pd.to_datetime(
    dict(year=metro_days_to_close_sm_week_df_clean["year"], month=metro_days_to_close_sm_week_df_clean["month"], day=1)
)

metro_market_temp_month_df_clean["date"] = pd.to_datetime(
    dict(year=metro_market_temp_month_df_clean["year"], month=metro_market_temp_month_df_clean["month"], day=1)
)

metro_new_con_sales_month_df_clean["date"] = pd.to_datetime(
    dict(year=metro_new_con_sales_month_df_clean["year"], month=metro_new_con_sales_month_df_clean["month"], day=1)
)

metro_zhvi_tier_month_df_clean["date"] = pd.to_datetime(
    dict(year=metro_zhvi_tier_month_df_clean["year"], month=metro_zhvi_tier_month_df_clean["month"], day=1)
)

metro_zordi_condo_month_df_clean["date"] = pd.to_datetime(
    dict(year=metro_zordi_condo_month_df_clean["year"], month=metro_zordi_condo_month_df_clean["month"], day=1)
)   

metro_zordi_mfr_month_df_clean["date"] = pd.to_datetime(
    dict(year=metro_zordi_mfr_month_df_clean["year"], month=metro_zordi_mfr_month_df_clean["month"], day=1)
)

metro_zordi_sfr_month_df_clean["date"] = pd.to_datetime(
    dict(year=metro_zordi_sfr_month_df_clean["year"], month=metro_zordi_sfr_month_df_clean["month"], day=1)
)

metro_zordi_all_month_df_clean["date"] = pd.to_datetime(
    dict(year=metro_zordi_all_month_df_clean["year"], month=metro_zordi_all_month_df_clean["month"], day=1)
)

In [23]:
metro_inventory_week_df_clean_wide = metro_inventory_week_df_clean[['date','RegionName','StateName','Inventory']].copy()
metro_inventory_week_df_clean_wide["market_group"] = np.where(metro_inventory_week_df_clean_wide["StateName"] == "FL", "FL", "Non_FL")
metro_inventory_week_df_clean_wide = (
    metro_inventory_week_df_clean_wide.pivot_table(index="date", columns="market_group", values="Inventory", aggfunc="mean")
    .reset_index()
)
us_df = metro_inventory_week_df_clean.groupby(["date"]).agg({"Inventory": "mean"}).reset_index()
metro_inventory_week_df_clean_wide = metro_inventory_week_df_clean_wide.merge(us_df, on="date", how="left")
metro_inventory_week_df_clean_wide.rename(columns={"Inventory": "Inventory_US"
                                                   ,"FL": "Inventory_FL"
                                                   ,"Non_FL": "Inventory_Non_FL"}, inplace=True)

In [24]:
metro_days_to_close_sm_week_df_clean_wide = metro_days_to_close_sm_week_df_clean[['date','RegionName','StateName','DaysToClose']].copy()
metro_days_to_close_sm_week_df_clean_wide["market_group"] = np.where(metro_days_to_close_sm_week_df_clean_wide["StateName"] == "FL", "FL", "Non_FL")
metro_days_to_close_sm_week_df_clean_wide = (
    metro_days_to_close_sm_week_df_clean_wide.pivot_table(index="date", columns="market_group", values="DaysToClose", aggfunc="mean")
    .reset_index()
)
us_df = metro_days_to_close_sm_week_df_clean.groupby(["date"]).agg({"DaysToClose": "mean"}).reset_index()
metro_days_to_close_sm_week_df_clean_wide = metro_days_to_close_sm_week_df_clean_wide.merge(us_df, on="date", how="left")
metro_days_to_close_sm_week_df_clean_wide.rename(columns={"DaysToClose": "DaysToClose_US"
                                                   ,"FL": "DaysToClose_FL"
                                                   ,"Non_FL": "DaysToClose_Non_FL"}, inplace=True)

In [25]:
metro_market_temp_month_df_clean_wide = metro_market_temp_month_df_clean[['date','RegionName','StateName','MarketTemp']].copy()
metro_market_temp_month_df_clean_wide["market_group"] = np.where(metro_market_temp_month_df_clean_wide["StateName"] == "FL", "FL", "Non_FL")
metro_market_temp_month_df_clean_wide = (
    metro_market_temp_month_df_clean_wide.pivot_table(index="date", columns="market_group", values="MarketTemp", aggfunc="mean")
    .reset_index()
)
us_df = metro_market_temp_month_df_clean.groupby(["date"]).agg({"MarketTemp": "mean"}).reset_index()
metro_market_temp_month_df_clean_wide = metro_market_temp_month_df_clean_wide.merge(us_df, on="date", how="left")
metro_market_temp_month_df_clean_wide.rename(columns={"MarketTemp": "MarketTemp_US"
                                                   ,"FL": "MarketTemp_FL"
                                                   ,"Non_FL": "MarketTemp_Non_FL"}, inplace=True)

In [26]:
metro_new_con_sales_month_df_clean_wide = metro_new_con_sales_month_df_clean[['date','RegionName','StateName','NewConSales']].copy()
metro_new_con_sales_month_df_clean_wide["market_group"] = np.where(metro_new_con_sales_month_df_clean_wide["StateName"] == "FL", "FL", "Non_FL")
metro_new_con_sales_month_df_clean_wide = (
    metro_new_con_sales_month_df_clean_wide.pivot_table(index="date", columns="market_group", values="NewConSales", aggfunc="mean")
    .reset_index()
)
us_df = metro_new_con_sales_month_df_clean.groupby(["date"]).agg({"NewConSales": "mean"}).reset_index()
metro_new_con_sales_month_df_clean_wide = metro_new_con_sales_month_df_clean_wide.merge(us_df, on="date", how="left")
metro_new_con_sales_month_df_clean_wide.rename(columns={"NewConSales": "NewConSales_US"
                                                   ,"FL": "NewConSales_FL"
                                                   ,"Non_FL": "NewConSales_Non_FL"}, inplace=True)

In [27]:
metro_zhvi_tier_month_df_clean_wide = metro_zhvi_tier_month_df_clean[['date','RegionName','StateName','ZHVI_Tier']].copy()
metro_zhvi_tier_month_df_clean_wide["market_group"] = np.where(metro_zhvi_tier_month_df_clean_wide["StateName"] == "FL", "FL", "Non_FL")
metro_zhvi_tier_month_df_clean_wide = (
    metro_zhvi_tier_month_df_clean_wide.pivot_table(index="date", columns="market_group", values="ZHVI_Tier", aggfunc="mean")
    .reset_index()
)
us_df = metro_zhvi_tier_month_df_clean.groupby(["date"]).agg({"ZHVI_Tier": "mean"}).reset_index()
metro_zhvi_tier_month_df_clean_wide = metro_zhvi_tier_month_df_clean_wide.merge(us_df, on="date", how="left")
metro_zhvi_tier_month_df_clean_wide.rename(columns={"ZHVI_Tier": "ZHVI_Tier_US"
                                                   ,"FL": "ZHVI_Tier_FL"
                                                   ,"Non_FL": "ZHVI_Tier_Non_FL"}, inplace=True)

In [28]:
metro_zordi_condo_month_df_clean_wide = metro_zordi_condo_month_df_clean[['date','RegionName','StateName','ZORDI_Condo']].copy()
metro_zordi_condo_month_df_clean_wide["market_group"] = np.where(metro_zordi_condo_month_df_clean_wide["StateName"] == "FL", "FL", "Non_FL")
metro_zordi_condo_month_df_clean_wide = (
    metro_zordi_condo_month_df_clean_wide.pivot_table(index="date", columns="market_group", values="ZORDI_Condo", aggfunc="mean")
    .reset_index()
)
us_df = metro_zordi_condo_month_df_clean.groupby(["date"]).agg({"ZORDI_Condo": "mean"}).reset_index()
metro_zordi_condo_month_df_clean_wide = metro_zordi_condo_month_df_clean_wide.merge(us_df, on="date", how="left")
metro_zordi_condo_month_df_clean_wide.rename(columns={"ZORDI_Condo": "ZORDI_Condo_US"
                                                   ,"FL": "ZORDI_Condo_FL"
                                                   ,"Non_FL": "ZORDI_Condo_Non_FL"}, inplace=True)

In [29]:
metro_zordi_mfr_month_df_clean_wide = metro_zordi_mfr_month_df_clean[['date','RegionName','StateName','ZORDI_MFR']].copy()
metro_zordi_mfr_month_df_clean_wide["market_group"] = np.where(metro_zordi_mfr_month_df_clean_wide["StateName"] == "FL", "FL", "Non_FL")
metro_zordi_mfr_month_df_clean_wide = (
    metro_zordi_mfr_month_df_clean_wide.pivot_table(index="date", columns="market_group", values="ZORDI_MFR", aggfunc="mean")
    .reset_index()
)
us_df = metro_zordi_mfr_month_df_clean.groupby(["date"]).agg({"ZORDI_MFR": "mean"}).reset_index()
metro_zordi_mfr_month_df_clean_wide = metro_zordi_mfr_month_df_clean_wide.merge(us_df, on="date", how="left")
metro_zordi_mfr_month_df_clean_wide.rename(columns={"ZORDI_MFR": "ZORDI_MFR_US"
                                                   ,"FL": "ZORDI_MFR_FL"
                                                   ,"Non_FL": "ZORDI_MFR_Non_FL"}, inplace=True)

In [30]:
metro_zordi_sfr_month_df_clean_wide = metro_zordi_sfr_month_df_clean[['date','RegionName','StateName','ZORDI_SFR']].copy()
metro_zordi_sfr_month_df_clean_wide["market_group"] = np.where(metro_zordi_sfr_month_df_clean_wide["StateName"] == "FL", "FL", "Non_FL")
metro_zordi_sfr_month_df_clean_wide = (
    metro_zordi_sfr_month_df_clean_wide.pivot_table(index="date", columns="market_group", values="ZORDI_SFR", aggfunc="mean")
    .reset_index()
)
us_df = metro_zordi_sfr_month_df_clean.groupby(["date"]).agg({"ZORDI_SFR": "mean"}).reset_index()
metro_zordi_sfr_month_df_clean_wide = metro_zordi_sfr_month_df_clean_wide.merge(us_df, on="date", how="left")
metro_zordi_sfr_month_df_clean_wide.rename(columns={"ZORDI_SFR": "ZORDI_SFR_US"
                                                   ,"FL": "ZORDI_SFR_FL"
                                                   ,"Non_FL": "ZORDI_SFR_Non_FL"}, inplace=True)

In [31]:
metro_zordi_all_month_df_clean_wide = metro_zordi_all_month_df_clean[['date','RegionName','StateName','ZORDI_All']].copy()
metro_zordi_all_month_df_clean_wide["market_group"] = np.where(metro_zordi_all_month_df_clean_wide["StateName"] == "FL", "FL", "Non_FL")
metro_zordi_all_month_df_clean_wide = (
    metro_zordi_all_month_df_clean_wide.pivot_table(index="date", columns="market_group", values="ZORDI_All", aggfunc="mean")
    .reset_index()
)
us_df = metro_zordi_all_month_df_clean.groupby(["date"]).agg({"ZORDI_All": "mean"}).reset_index()
metro_zordi_all_month_df_clean_wide = metro_zordi_all_month_df_clean_wide.merge(us_df, on="date", how="left")
metro_zordi_all_month_df_clean_wide.rename(columns={"ZORDI_All": "ZORDI_All_US"
                                                   ,"FL": "ZORDI_All_FL"
                                                   ,"Non_FL": "ZORDI_All_Non_FL"}, inplace=True)

In [ ]:
BLS_unemployment_data_df_clean = BLS_unemployment_data_df.copy(deep=True)

BLS_unemployment_data_df_clean = pd.melt(BLS_unemployment_data_df_clean,
                                 id_vars=["State","Area"],
                                 var_name="Month",
                                 value_name="Unemployment_Rate")

# statiscal area names were cleaned for join but there is not a 1 for 1 match. One example is below.
# Alachua is an example of a county not in earnings data
# BLS_weekly_earnings_df_clean[BLS_weekly_earnings_df_clean['State']=='Florida']['Area'].unique()

BLS_unemployment_data_df_clean['Area'] = BLS_unemployment_data_df_clean['Area'].str.replace(" Metropolitan Statistical Area", "", regex=False)

In [69]:
BLS_weekly_earnings_df_clean = BLS_weekly_earnings_df.copy(deep=True)

BLS_weekly_earnings_df_clean['Area'] = np.where(
    BLS_weekly_earnings_df_clean['Area'] == 'Statewide',
    BLS_weekly_earnings_df_clean['State'],
    BLS_weekly_earnings_df_clean['Area']
)

BLS_weekly_earnings_df_clean = pd.melt(BLS_weekly_earnings_df_clean,
                                 id_vars=["State","Area"],
                                 var_name="Month",
                                 value_name="Earnings")

In [ ]:
BLS_df_clean_merge = pd.merge(BLS_weekly_earnings_df_clean,BLS_unemployment_data_df_clean,how="outer", on=["State","Area","Month"])
BLS_df_clean_merge.shape

In [1]:
import pandas as pd
url = "https://econdata.s3-us-west-2.amazonaws.com/Reports/Core/RDC_Inventory_Core_Metrics_Zip_History.csv"
df = pd.read_csv(url)

:

# Start total dataframe cleaning

In [ ]:
#DFs to add
BLS_df_clean_merge

In [36]:
dfs = [
hurricanes_df_clean,
unemployment_df_clean,
fl_building_permits_df_clean,
hpi_df_clean,
investor_df_clean,
metro_inventory_week_df_clean,
metro_days_to_close_sm_week_df_clean,
metro_market_temp_month_df_clean,
metro_new_con_sales_month_df_clean,
metro_zhvi_tier_month_df_clean,
metro_zordi_condo_month_df_clean,
metro_zordi_mfr_month_df_clean,
metro_zordi_sfr_month_df_clean,
metro_zordi_all_month_df_clean
]

max_min_date = max(df["date"].min() for df in dfs)

min_max_date = min(df["date"].max() for df in dfs)

print("Maximum of Minimum Dates:", max_min_date)
print("Minimum of Maximum Dates:", min_max_date)

Maximum of Minimum Dates: 2020-06-01 00:00:00
Minimum of Maximum Dates: 2024-10-01 00:00:00

In [37]:
hurricanes_df_clean = hurricanes_df_clean[hurricanes_df_clean["date"] >= max_min_date]
unemployment_df_clean = unemployment_df_clean[unemployment_df_clean["date"] >= max_min_date]
fl_building_permits_df_clean = fl_building_permits_df_clean[fl_building_permits_df_clean["date"] >= max_min_date]
hpi_df_clean = hpi_df_clean[hpi_df_clean["date"] >= max_min_date]
investor_df_clean = investor_df_clean[investor_df_clean["date"] >= max_min_date]
metro_inventory_week_df_clean = metro_inventory_week_df_clean[metro_inventory_week_df_clean["date"] >= max_min_date]
metro_days_to_close_sm_week_df_clean = metro_days_to_close_sm_week_df_clean[metro_days_to_close_sm_week_df_clean["date"] >= max_min_date]
metro_market_temp_month_df_clean = metro_market_temp_month_df_clean[metro_market_temp_month_df_clean["date"] >= max_min_date]
metro_new_con_sales_month_df_clean = metro_new_con_sales_month_df_clean[metro_new_con_sales_month_df_clean["date"] >= max_min_date]
metro_zhvi_tier_month_df_clean = metro_zhvi_tier_month_df_clean[metro_zhvi_tier_month_df_clean["date"] >= max_min_date]
metro_zordi_condo_month_df_clean = metro_zordi_condo_month_df_clean[metro_zordi_condo_month_df_clean["date"] >= max_min_date]
metro_zordi_mfr_month_df_clean = metro_zordi_mfr_month_df_clean[metro_zordi_mfr_month_df_clean["date"] >= max_min_date]
metro_zordi_sfr_month_df_clean = metro_zordi_sfr_month_df_clean[metro_zordi_sfr_month_df_clean["date"] >= max_min_date]
metro_zordi_all_month_df_clean = metro_zordi_all_month_df_clean[metro_zordi_all_month_df_clean["date"] >= max_min_date]

In [38]:
hurricanes_df_clean = hurricanes_df_clean[["date", "highest_category"]]

unemployment_df_clean = unemployment_df_clean[["date", "FLUR"]]

fl_building_permits_df_clean = fl_building_permits_df_clean[["date", "FLBP1FH"]]

hpi_df_clean = hpi_df_clean[["date", "Location", "HPI"]]

metro_inventory_week_df_clean.drop(columns=["year", "month"], inplace=True)
metro_days_to_close_sm_week_df_clean.drop(columns=["year", "month"], inplace=True)
metro_market_temp_month_df_clean.drop(columns=["year", "month"], inplace=True)
metro_new_con_sales_month_df_clean.drop(columns=["year", "month"], inplace=True)
metro_zhvi_tier_month_df_clean.drop(columns=["year", "month"], inplace=True)
metro_zordi_condo_month_df_clean.drop(columns=["year", "month"], inplace=True)
metro_zordi_mfr_month_df_clean.drop(columns=["year", "month"], inplace=True)
metro_zordi_sfr_month_df_clean.drop(columns=["year", "month"], inplace=True)
metro_zordi_all_month_df_clean.drop(columns=["year", "month"], inplace=True)

/tmp/ipykernel_1982/196132387.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metro_inventory_week_df_clean.drop(columns=["year", "month"], inplace=True)
/tmp/ipykernel_1982/196132387.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metro_days_to_close_sm_week_df_clean.drop(columns=["year", "month"], inplace=True)
/tmp/ipykernel_1982/196132387.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metro_market_temp_month_df_clean.drop(columns=["year", "month"], inplace=True)
/tmp/ipykernel_1982/196132387.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metro_new_con_sales_month_df_clean.drop(columns=["year", "month"], inplace=True)
/tmp/ipykernel_1982/196132387.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metro_zhvi_tier_month_df_clean.drop(columns=["year", "month"], inplace=True)

In [39]:
investor_df_clean["state"] = investor_df_clean["state"].astype(str)

/tmp/ipykernel_1982/1942640330.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  investor_df_clean["state"] = investor_df_clean["state"].astype(str)

In [40]:
investor_df_clean_wide = investor_df_clean.copy(deep=True)

investor_df_clean_wide_FL = investor_df_clean_wide[investor_df_clean_wide["state"].str.strip() == "FL"].copy()
investor_df_clean_wide_Total = investor_df_clean_wide.copy()
investor_df_clean_wide_Total = investor_df_clean_wide_Total.groupby("date").agg({
    "Investor Purchases": "sum",
    "Investor Market Share": "mean",
    "Investor Purchases YoY": "mean"
}).reset_index()

investor_df_clean_wide = pd.merge(investor_df_clean_wide_FL,investor_df_clean_wide_Total, how="outer", on="date", suffixes=("_FL", "_Total"))
investor_df_clean_wide = investor_df_clean_wide.drop(columns=["state"])

In [41]:
#NSA = Not Seasonally Adjusted.
#SA = Seasonally Adjusted.

hpi_df_clean_wide = hpi_df_clean.copy(deep=True)
hpi_df_clean_wide = hpi_df_clean_wide[hpi_df_clean_wide['Location'].isin(['USA  (SA)','USA  (NSA)','South Atlantic (SA)','South Atlantic (NSA)'])].pivot(index="date", columns="Location", values="HPI").reset_index()
hpi_df_clean_wide.columns = ["date", "HPI_South_Atlantic_Not_Seasonally_Adjusted", "HPI_South_Atlantic_Seasonally_Adjusted", "HPI_USA_Not_Seasonally_Adjusted", "HPI_USA_Seasonally_Adjusted"]

# Documentation of dataframes


### hurricanes_df_clean
- Huricane landfalls in Florida by month. A null value indicates no landfalls, a value idicates the Saffir-Simpson U.S. Category.

### unemployment_df_clean
- Florida unemployment rate by month.

### fl_building_permits_df_clean

### hpi_df_clean

## Zillow 
- details on Zillow data can be found here: https://www.zillow.com/research/data/

### metro_inventory_week_df_clean
- For sale inventory by month by region.

### metro_days_to_close_sm_week_df_clean
- Days to close housing sale by month by region.
- Days to close = Mean number of days between the listing going pending and the sale date.

### metro_market_temp_month_df_clean
- MarketTemp according to Zillow, "...aims to capture the balance of for-sale supply and demand in a given market. A higher number means the market is more tilted in favor of sellers. It relies on a combination of engagement and listing performance inputs to provide insights into current market dynamics."

### metro_new_con_sales_month_df_clean

#metro_zhvi_tier_month_df_clean
#metro_zordi_condo_month_df_clean
#metro_zordi_mfr_month_df_clean
#metro_zordi_sfr_month_df_clean
#metro_zordi_all_month_df_clean

In [42]:
# Base non-Zillow datasets
base_data_sets_to_merge = {
    "unemployment_df_clean": unemployment_df_clean,
    "fl_building_permits_df_clean": fl_building_permits_df_clean,
    "investor_df_clean_wide": investor_df_clean_wide,
    "hpi_df_clean_wide": hpi_df_clean_wide
}

# Start with hurricanes
processed_data = hurricanes_df_clean.copy()

# Merge base datasets on date using outer join
for name, df in base_data_sets_to_merge.items():
    processed_data = pd.merge(processed_data, df, on="date", how="outer")
    print(f"After merging {name}:", processed_data.shape)

# Zillow datasets to merge on date using inner join
zillow_data_sets_to_merge = {
    "metro_inventory_week_df_clean_wide": metro_inventory_week_df_clean_wide,
    "metro_days_to_close_sm_week_df_clean_wide": metro_days_to_close_sm_week_df_clean_wide,
    "metro_market_temp_month_df_clean_wide": metro_market_temp_month_df_clean_wide,
    "metro_new_con_sales_month_df_clean_wide": metro_new_con_sales_month_df_clean_wide,
    "metro_zhvi_tier_month_df_clean_wide": metro_zhvi_tier_month_df_clean_wide,
    "metro_zordi_condo_month_df_clean_wide": metro_zordi_condo_month_df_clean_wide,
    "metro_zordi_mfr_month_df_clean_wide": metro_zordi_mfr_month_df_clean_wide,
    "metro_zordi_sfr_month_df_clean_wide": metro_zordi_sfr_month_df_clean_wide,
    "metro_zordi_all_month_df_clean_wide": metro_zordi_all_month_df_clean_wide
}

for name, df in zillow_data_sets_to_merge.items():
    processed_data = pd.merge(processed_data, df, on="date", how="inner")
    print(f"After merging {name}:", processed_data.shape)

processed_data.head(5)

After merging unemployment_df_clean: (66, 3)
After merging fl_building_permits_df_clean: (67, 4)
After merging investor_df_clean_wide: (67, 10)
After merging hpi_df_clean_wide: (67, 14)
After merging metro_inventory_week_df_clean_wide: (67, 17)
After merging metro_days_to_close_sm_week_df_clean_wide: (67, 20)
After merging metro_market_temp_month_df_clean_wide: (67, 23)
After merging metro_new_con_sales_month_df_clean_wide: (67, 26)
After merging metro_zhvi_tier_month_df_clean_wide: (67, 29)
After merging metro_zordi_condo_month_df_clean_wide: (67, 32)
After merging metro_zordi_mfr_month_df_clean_wide: (67, 35)
After merging metro_zordi_sfr_month_df_clean_wide: (67, 38)
After merging metro_zordi_all_month_df_clean_wide: (67, 41)

,date,highest_category,FLUR,FLBP1FH,Investor Purchases_FL,Investor Market Share_FL,Investor Purchases YoY_FL,Investor Purchases_Total,Investor Market Share_Total,Investor Purchases YoY_Total,...,ZORDI_Condo_US,ZORDI_MFR_FL,ZORDI_MFR_Non_FL,ZORDI_MFR_US,ZORDI_SFR_FL,ZORDI_SFR_Non_FL,ZORDI_SFR_US,ZORDI_All_FL,ZORDI_All_Non_FL,ZORDI_All_US
0,2020-06-01,NaN,11.6,8764,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,101.288000,98.95,102.803681,102.580925,118.500000,200.003279,194.057751,101.708333,134.293103,132.690574
1,2020-07-01,NaN,11.6,9864,10876,15.833333,-13.833333,55548,10.840909,-13.772727,...,106.889831,99.20,113.993865,113.138728,119.916667,207.057325,200.869822,102.625000,143.036170,141.072874
2,2020-08-01,NaN,8.6,10100,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,99.054264,102.05,120.743902,119.669540,115.416667,191.336207,186.438172,97.958333,141.852391,139.766337
3,2020-09-01,2.0,8.0,10633,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,92.846154,101.85,118.490854,117.534483,112.541667,173.470270,169.758883,94.166667,132.022587,130.244618
4,2020-10-01,NaN,6.9,11596,12352,18.0,-4.5,61847,12.130682,-0.085227,...,87.000000,95.35,104.338762,103.788991,104.916667,155.027100,151.966921,87.041667,116.691837,115.307393

// Notes
- add base sets into low data.

base_data_sets_to_merge = {
    "unemployment_df_clean": unemployment_df_clean,
    "fl_building_permits_df_clean": fl_building_permits_df_clean,
    "investor_df_clean_wide": investor_df_clean_wide,
    "hpi_df_clean_wide": hpi_df_clean_wide
}

In [43]:
data_sets_to_merge_low = {
    "metro_new_con_sales_month_df_clean": metro_new_con_sales_month_df_clean,
    "metro_zhvi_tier_month_df_clean": metro_zhvi_tier_month_df_clean,
    "metro_zordi_condo_month_df_clean": metro_zordi_condo_month_df_clean,
    "metro_zordi_mfr_month_df_clean": metro_zordi_mfr_month_df_clean,
    "metro_zordi_sfr_month_df_clean": metro_zordi_sfr_month_df_clean,
    "metro_zordi_all_month_df_clean": metro_zordi_all_month_df_clean
}

cols = ["date", "RegionID", "SizeRank", "RegionName", "RegionType", "StateName", "Month"]

processed_data_low = metro_market_temp_month_df_clean.copy()

for name, df in data_sets_to_merge_low.items():
    processed_data_low = pd.merge(processed_data_low, df, on=cols, how="outer")
    print(f"After merging {name}:", processed_data_low.shape)
    
processed_data_low = pd.merge(processed_data_low, metro_days_to_close_sm_week_df_clean, on=[col for col in cols if col != "Month"], how="outer")

processed_data_low = processed_data_low[processed_data_low['RegionName']!='United States']

processed_data_low.head(5)

After merging metro_new_con_sales_month_df_clean: (62206, 9)
After merging metro_zhvi_tier_month_df_clean: (62739, 10)
After merging metro_zordi_condo_month_df_clean: (62789, 11)
After merging metro_zordi_mfr_month_df_clean: (62853, 12)
After merging metro_zordi_sfr_month_df_clean: (62856, 13)
After merging metro_zordi_all_month_df_clean: (62896, 14)

,RegionID,SizeRank,RegionName,RegionType,StateName,Month,MarketTemp,date,NewConSales,ZHVI_Tier,ZORDI_Condo,ZORDI_MFR,ZORDI_SFR,ZORDI_All,DaysToClose
1,394297,677,"Aberdeen, SD",msa,SD,2020-06-30,59.0,2020-06-01,NaN,171702.082197,NaN,NaN,NaN,NaN,NaN
2,394298,473,"Aberdeen, WA",msa,WA,2020-06-30,97.0,2020-06-01,NaN,235972.537055,NaN,NaN,NaN,NaN,NaN
3,394299,251,"Abilene, TX",msa,TX,2020-06-30,59.0,2020-06-01,34.0,152751.072291,NaN,71.0,104.0,94.0,NaN
4,394300,720,"Ada, OK",msa,OK,2020-06-30,73.0,2020-06-01,NaN,125912.908639,NaN,NaN,NaN,NaN,NaN
5,394302,393,"Adrian, MI",msa,MI,2020-06-30,108.0,2020-06-01,NaN,164669.930398,NaN,NaN,NaN,NaN,NaN

In [44]:
# Saving data as csv in the processed folder
processed_data.to_csv("../data/processed/processed_data.csv", index=False)
processed_data_low.to_csv("../data/processed/processed_data_low.csv", index=False)